- README.md
- site/content/resources.md
Resolves techqueria/website#13.
Resources added: 
---
> Add new resources

- CONTRIBUTING.md
- README.md
> #20 - Added waffle.io links and badges in readme and contributing

- site/content/media-kit.md
Rich dynamic embed for Imgur album instead of static link
---
> Add Imgur album as embed

- README.md
- site/content/sponsors.md
Amending copy in sponsors page and adding myself as contributor
---
> Amending copy on sponsors page

- site/layouts/_default/baseof.html
- site/layouts/partials/head.html
Adds google analytics to the page 
* [*] Checked to [see if a similar PR has already been opened](https://github.com/techqueria/website/pulls) 🤔️
* [*] Reviewed the [contributing guidelines](https://github.com/techqueria/website/blob/master/CONTRIBUTING.md) 🔍️
* [*] Added my name to the bottom of the list under the **Credits** section in the [README.md](https://github.com/techqueria/website/blob/master/README.md) with a link to my website or GitHub profile 👥️
> closes #37 added google analytics tag

- README.md
- site/content/sponsors/braintree.md
- site/content/sponsors/caremessage.md
- site/content/sponsors/cisco-systems-meraki.md
- site/content/sponsors/climate-corporation.md
- site/content/sponsors/dropbox.md
- site/content/sponsors/google.md
- site/content/sponsors/informedk12.md
- site/content/sponsors/lending-club.md
- site/content/sponsors/lumonsity.md
- site/content/sponsors/twilio.md
- site/content/sponsors/walmart.md
> Update sponsor list

- src/sass/_card.scss
Addresses #56 
Updated card-image height in sponsor page
Updated card-image height in communities page
Signed-off-by: db118 <drrylbalderas@gmail.com>
> Update card-image height

- src/sass/_card.scss
Reverts techqueria/website#57
Just until @db118 creates a fix which will be amazing! 🙏🏽️
> Revert "Update card-image height"

- README.md
As @fvntr mentioned in Slack, would be great to also have a dedicated page to past organizers/developers/etc to show them appreciation.
This small change updates who has made a contribution to most recent version of the website.
---
> Updating list of devs

- site/content/press/2018-02-24.md
Added a yahoo article that mentions techqueria 
---
> added a yahoo! article

- site/content/communities/facebook-group.md
- site/content/communities/facebook-page.md
Didn't realize we had a FB page so I'm adding that on too!
Creates aliases so old links aren't broken. 
/facebook/ will route to Facebook Group.
---
> Add Facebook Page to Communitites

- site/content/resources/design/latinxs-who-design.md
Insert description of PR here
Adding Latinxs Who Design to design resources 
---
* [x ] Checked to [see if a similar PR has already been opened](https://github.com/techqueria/website/pulls) 🤔️
* [x ] Reviewed the [contributing guidelines](https://github.com/techqueria/website/blob/master/CONTRIBUTING.md) 🔍️
* [ x] Added my name to the bottom of the list under the **Credits** section in the [README.md](https://github.com/techqueria/website/blob/master/README.md) with a link to my website or GitHub profile 👥️
> Adding Latinxs Who Design in Resources

- site/layouts/partials/content/card/_index.html
- site/layouts/partials/content/card/card.event.html
- src/sass/_card.scss
Address #56 
Signed-off-by: db118 <drrylbalderas@gmail.com>
* [ X] Checked to [see if a similar PR has already been opened](https://github.com/techqueria/website/pulls) 🤔️
* [X ] Reviewed the [contributing guidelines](https://github.com/techqueria/website/blob/master/CONTRIBUTING.md) 🔍️
* [X ] Added my name to the bottom of the list under the **Credits** section in the [README.md](https://github.com/techqueria/website/blob/master/README.md) with a link to my website or GitHub profile 👥️
> Fix inconsistent card-image height

- _redirects
Created a _redirects file so that every requests to beta. or www. is redirected to the main domain. 
---
> Created redirect file for netlify

- site/content/about/_index.md
- site/content/sponsors/_index.md
> Updating organizer info in about page 

- site/content/events/2018-10-17.md
Addresses https://github.com/techqueria/website/issues/78
---
> Adding mixpanel sf event

- CONTRIBUTING.md
- README.md
> Credits -> Contributors

- site/layouts/partials/content/card/card.event.html
This pr removes the rsvp button 
---
> Removing rsvp for past events

- site/content/resources/open-source/_index.md
- site/content/resources/open-source/operation-code.md
Addressing issue  #75 
Signed-off-by: darrylbalderas <drrylbalderas@gmail.com>
---
> Create initial open source page

- README.md
Adding GitHub marketplace apps
- FOSSA https://app.fossa.io/projects/git%2Bgithub.com%2Ftechqueria%2Fwebsite/refs/branch/master/172bd081a845cdf03d552618675922a7c8e559c2
Updating Waffle badge to have same flat square formatting
---
> Add FOSSA status, update Waffle badge

- _redirects
- netlify.toml
- src/sass/_header.scss
- src/sass/_section.scss
- fix codefactor quality issues
- add back redirects file
---
> fix code factor issues

- README.md
- site/content/resources/open-source/operation-code.md
Just using a cacheable image link.
---
> Use s3 link for Operation Code logo

- site/config.toml
> Making some seo changes

- site/layouts/partials/footer/who-we-are.html
> updated footer verbiage

- site/config.toml
> more seo changes

- site/config.toml
This is asscociated to the nav menu pr
---
> changing toml config file for header menu

- site/content/resources/health/_index.md
Fixing HOPE health resource link
---
> fixing hope link

- site/content/sponsors/informedk12.md
- site/content/sponsors/mixpanel.md
Added mixpanel to the list of sponsors
---
> Added Mixpanel to sponsors

- README.md
- site/content/communities/eventbrite-nyc.md
- site/content/communities/eventbrite.md
- site/content/communities/facebook-group.md
- site/content/communities/facebook-page.md
- site/content/communities/github.md
- site/content/communities/linkedin.md
- site/content/communities/meetup.md
- site/content/communities/newsletter.md
- site/content/communities/slack.md
- site/content/communities/twitter-la.md
- site/content/communities/twitter-nyc.md
- site/content/communities/twitter-sf.md
- site/content/communities/youtube.md
- site/layouts/partials/footer/communities.html
- src/sass/_icons.scss
- src/sass/_variables.scss
> Resolving issue 158. Upon convo, we decided to keep original sorting but adding white logos after.

- site/layouts/partials/footer/copyright.html
Changing established date, its actually 2015
---
> Changing established date

- site/content/communities/newsletter.md
- src/sass/_overrides.scss
> Add new newsletter link

- src/sass/_overrides.scss
> inherit font size for subtitles

- site/layouts/partials/content/person.html
> fix author link

- .history/_redirects_20181016195755
- _redirects
Attempts to fix the file that controls the _redirects in netlifly 
---
> Fixed _redirects file for netlifly #185

- site/content/about/_index.md
Adding Hector to Our Story
---
> Adding Hector to Our Story section

- site/content/about/_index.md
> Changing est year in header

- package.json
@fvntr Hoping this fixes https://latinos.slack.com/archives/CBPG4HVA7/p1545113755000600
> gulp cli addition

- site/content/events/2019-01-30.md
> Adding Austin event

- site/content/communities/slack.md
Aloha messages are for new Slack users and they're super useful
---
> update aloha messages

- site/content/communities/_index.es.md
- site/content/events/_index.es.md
- site/content/people/_index.es.md
- site/content/photos/_index.es.md
- site/content/press/_index.es.md
- site/content/resources/_index.es.md
- site/content/sponsors/_index.es.md
- site/content/testimonials/_index.es.md
- Helps with issue #236.
- Adds translations of some of the menu options' descriptions.
> Adds translations for the menu options' descriptions.

- config.toml
- content/_index.es.md
- content/code-of-conduct.es.md
- content/contact.es.md
- i18n/en.toml
- i18n/es.toml
- layouts/404.html
- layouts/index.html
- layouts/partials/content/cta/cta.newsletter.html
- layouts/partials/content/cta/cta.slack.html
- layouts/partials/content/cta/cta.sponsor.html
Description:
- Adds to issue #236.
- Translates updated Code of Conduct.
- Translates slack, newsletter and sponsor information from the Home Page.
- Various small translation fixes.
> Eng spa translations2

- config.toml
- content/about/_index.es.md
- content/events/_index.es.md
- i18n/en.toml
- i18n/es.toml
- layouts/404.html
- layouts/partials/content/footer/contribute.html
- layouts/partials/content/footer/sponsor-us.html
- layouts/partials/content/footer/subscribe.html
- layouts/partials/footer/communities.html
- layouts/partials/footer/copyright.html
- layouts/partials/footer/sitemap.html
- Adds to issue #236. 
- Translates the following files:
- sponsor-us.html
- subscribe.html
- contribute.html
- copyright.html
- sitemap.html
- communities.html
- Adds various small translations fixes.
> Eng spa translations3

- .github/CONTRIBUTING.md
- .github/config.yml
- content/code-of-conduct.es.md
- content/communities/newsletter.md
- content/contact.es.md
- content/contact.md
- content/photos/_index.es.md
- content/press/_index.es.md
- content/resources/_index.es.md
- layouts/partials/content/footer/subscribe.html
> fix bug with translations

- .github/CONTRIBUTING.md
- content/communities/chapters/_index.es.md
- content/communities/chapters/bay-area/_index.es.md
- content/communities/chapters/los-angeles/_index.es.md
- content/communities/chapters/los-angeles/la-events/_index.es.md
- content/communities/chapters/new-york-city/_index.es.md
- content/communities/facebook-group/_index.es.md
- content/communities/linkedin-group/_index.es.md
- content/communities/linkedin/_index.es.md
- content/communities/slack/_index.es.md
Signed-off-by: Frances Coronel <fcoronel@slack-corp.com>
---
> fix url issue

- README.md
- config.toml
Emojis removed from items in dropdowns
- Fixes #331 
---
> emojis removed from nav bar dropdowns

- README.md
- content/communities/slack/_index.md
Added Slofile profile link in Slack page. 
Fixes #335 
---
> Updating slack page

- README.md
- config.toml
- content/resources/conferences/_index.md
- content/resources/conferences/latin-tech-conference-latinx-tech-summit.md
- content/resources/conferences/latinotech-latinx-tech-summit.md
- content/resources/conferences/ltx-latinx-tech-summit.md
- content/resources/conferences/lulacs-latinx-tech-summit.md
- content/resources/conferences/lxai-lainx-tech-summit.md
fixes# 343
This creates a "Conferences" page under Resources...
https://techqueria.org/resources/conferences
Initially this page will contain the following Latinx Tech Summit Organizations in card format with title, description, and link to website. The following initial organizations are as follows:  
1. http://ltx-latinx-in-tech-summit.eventcreate.com/
2. https://www.latinxinai.org/
3. https://latintech.io/
4. http://www.latinotech.org/
5. https://www.latinxtechsummit.org/
---
- [X ] Checked to [see if a similar PR has already been opened](https://github.com/techqueria/website/pulls) 🤔️
- [ X] Reviewed the [contributing guidelines](https://github.com/techqueria/website/blob/master/.github/CONTRIBUTING.md) 🔍️
- [X ] Added my name …
> add new resource page for conferences

- README.md
Added my name and GitHub profile link to the README.md file
Thank you for the opportunity to contribute to my first open source project.
---
> Add my name to Contributors

- config.toml
- content/resources/similar-organizations/_index.md
- content/resources/similar-organizations/alpfa-organization.md
- content/resources/similar-organizations/latinas-in-tech-organization.md
- content/resources/similar-organizations/latinx-founders-collective-organization.md
- content/resources/similar-organizations/loft-coder-summit-organization.md
- content/resources/similar-organizations/society-of-hispanic-professional-engineers.md
- content/resources/similar-organizations/technolochicas-organization.md
Fixes Issue #336
This creates a "Similar Organizations" page under Resources...
https://techqueria.org/resources/similar-organizations/
Initially this page will contain the following Similar Organizations in card format with title, description, and link to website. The following initial organizations are as follows:
1. Latinas in Tech - https://www.latinasintech.org/
2. SHPE - https://www.shpeconnect.org
3. LOFT Coder Summit - https://www.loftcsl.org/programs/loft-coder-summit/
4. TECHNOLOchicas - https://technolochicas.org/
5. ALPFA - https://www.alpfa.org/
6. Latinx Founders Collective - https://www.latinxfounders.co/
---
> Add new Similar Organizations page under Resources

- config.toml
- content/about/contact.es.md
- content/about/shop.es.md
- content/about/shop.md
- content/donate/patreon-supporters/henry-idrovo.md
- content/support-us/_index.es.md
- layouts/_default/single.html
- layouts/partials/base/head/seo.html
Signed-off-by: Frances Coronel <fcoronel@slack-corp.com>
form names for netlify
---
> Consistent form names

- assets/sass/_navbar.scss
- assets/sass/_utilities.scss
- assets/sass/_variables.scss
- layouts/partials/base/navbar.html
> a more responsive navbar

- content/events/2019-05-14-nyc-panel-management.md
> added new nyc may event

- config.toml
- content/support-us/donate-space.es.md
- content/support-us/donate-space.md
- content/support-us/volunteer.es.md
- content/support-us/volunteer.md
Signed-off-by: Frances Coronel <fcoronel@slack-corp.com>
---
> Capitalization and form field updates

- README.md
- content/events/_index.md
Adds a google calendar to events page
- Fixes #367
---
> Added link to google calendar

- .vscode/settings.json
- content/english/events/2017-03-28-panel-mayor-oakland.md
- content/espanol/events/2017-03-28-panel-mayor-oakland.md
- layouts/partials/base/head/structured-data.html
> better structured data

- .github/ISSUE_TEMPLATE/translation-report.md
- i18n/en.toml
- i18n/es.toml
- layouts/partials/cta/cta.shop.html
Signed-off-by: Frances Coronel <fcoronel@slack-corp.com>
---
> Add translation report, fix CTA shop

- content/english/support-us/_index.md
- content/espanol/support-us/_index.md
- static/_redirects
- add deploy preview redirect
- fix form name duplications
---
> Minor form optimizations

- .github/CONTRIBUTING.md
- i18n/en.toml
- i18n/es.toml
> update contributing guidelines

- README.md
- config.toml
- content/english/communities/chapters/austin.md
- content/english/communities/chapters/bay-area.md
- content/english/communities/chapters/chicago.md
- content/english/communities/chapters/la.md
- content/english/communities/chapters/nyc.md
- content/english/communities/slack.md
- content/espanol/communities/chapters/austin.md
- content/espanol/communities/chapters/chicago.md
- content/espanol/communities/slack.md
techqueria.slack.com instead of latinos.slack.com
---
> updating Slack URL

- content/english/team/dalia-icedo.md
- content/english/team/hector-carmona.md
- content/english/team/josue-bustos.md
- content/english/team/kevin-hernandez.md
- content/english/team/phillip-ventura.md
- content/english/team/rubi-sanchez.md
- content/espanol/team/dalia-icedo.md
- content/espanol/team/hector-carmona.md
- content/espanol/team/josue-bustos.md
- content/espanol/team/kevin-hernandez.md
- content/espanol/team/phillip-ventura.md
- content/espanol/team/rubi-sanchez.md
update status of team members
---
> update team members

- layouts/shortcodes/fields/instagram.html
- layouts/shortcodes/fields/linkedin.html
- layouts/shortcodes/fields/twitter.html
> Fix pattern validation

- content/english/success/_index.md
- content/english/support-us/speak.md
- layouts/shortcodes/fields/instagram.html
- layouts/shortcodes/fields/linkedin.html
- layouts/shortcodes/fields/twitter.html
- pattern validation
- website field for speakers
- margin bottom for form success submission page
---
> add website to speak page

- layouts/shortcodes/fields/instagram.html
- layouts/shortcodes/fields/linkedin.html
- layouts/shortcodes/fields/twitter.html
- remove helper text for better consistency
---
> more field updates

- content/english/support-us/volunteer.md
- layouts/shortcodes/fields/instagram.html
- layouts/shortcodes/fields/linkedin.html
- layouts/shortcodes/fields/twitter.html
- layouts/shortcodes/fields/volunteer.html
- layouts/shortcodes/fields/website.html
- helper text back in
- copy updates
- volunteering form on top, roles on bottom
---
> Adding back helper text and making signing up to volunteer more prominent

- layouts/partials/base/footer/social-icons.html
> Fix footer links

- content/english/events/2017-03-23-understanding-encryption.md
- content/english/events/2017-05-25-tech-immigration.md
- content/english/events/2017-06-21-fintech-braintree.md
> fvntr: fixing some event dates

- content/english/events/2019-08-19-comida-meetup.md
Changing the description for this
---
> fvntr: changing dominicanx brunch description

- config.toml
- content/english/events/_index.md
- layouts/partials/base/head/_index.html
- layouts/section/events-paginator.html
> events update

- content/english/communities/slack/join.md
unique form name for slack signups
---
> form name update

- config.toml
- content/espanol/communities/slack.md
- layouts/partials/content/cta/cta.newsletter.html
- layouts/shortcodes/fields/location.html
> update newsletter link

- layouts/shortcodes/fields/member.html
> fix age discrepancy

- content/english/communities/slack/join.md
- content/english/support-us/speak.md
- layouts/shortcodes/fields/latinx.html
- layouts/shortcodes/fields/latinx_in_tech.html
- layouts/shortcodes/fields/tech.html
clarifying this question due to some confusion
---
> fvntr: changing question copy

- content/espanol/about/terms-of-service.md
- content/espanol/join/_index.md
- content/espanol/shop/_index.md
- updating Spanish translations for COC, become a member, enable JS
> spanish translations updated

- content/english/events/2019-10-17-climate-corporation.md
This PR adds a photos link for the Latinx in Product event and would close https://github.com/techqueria/website/issues/554
---
- [] Added my name to the bottom of the list under the **Contributors** section in the [README.md](https://github.com/techqueria/website/blob/master/README.md) with a link to my personal website or GitHub profile 👥️ (Optional)
> Add photos link to latinx in product event

- content/english/supporters/adobe.md
reflecting adobe sponsorship change
---
> fvntr: fixing adobe level

- README.md
- layouts/shortcodes/fields/linkedin.html
Updated regex to support latin characters, referenced: https://stackoverflow.com/questions/20690499/concrete-javascript-regex-for-accented-characters-diacritics
---
> Fixes unsupported accent characters in linkedin form

- content/english/join/_index.md
fixing a join slack redirect issue
---
> fvntr: adding redirect for join page

- assets/sass/_variables.scss
- content/english/support-us/corporate-partner/core-packages/diamond.md
- content/english/support-us/corporate-partner/core-packages/gold.md
- content/english/support-us/corporate-partner/core-packages/platinum.md
- content/english/support-us/corporate-partner/core-packages/silver.md
- content/english/support-us/corporate-partner/core-packages/titanium.md
- content/english/support-us/software-sponsor/honeybook.md
- layouts/partials/content/custom/supporters-showcase.html
> fix image and time estimate

- content/english/support-us/corporate-partner/marketing-packages/email-newsletter.md
- content/english/support-us/corporate-partner/marketing-packages/social-media.md
> change pricing

- content/english/support-us/chapter-director/application.md
> fix success page for chapter director application

- content/english/support-us/chapter-director/_index.md
- content/english/support-us/chapter-director/application.md
- content/english/support-us/chapter-director/chapter-tiers.md
> overly generous

- content/english/support-us/chapter-director/reimbursement-policy/_index.md
> script update

- content/english/support-us/chapter-director/_index.md
- content/english/support-us/chapter-director/chapter-director-application.md
- content/english/support-us/chapter-director/chapter-tiers.md
- content/english/support-us/chapter-director/reimbursement-policy/_index.md
- content/english/support-us/corporate-partner/custom-packages.md
- content/english/support-us/speak.md
- layouts/_default/baseof.html
- layouts/partials/base/footer/netlify.html
- layouts/partials/content/custom/partnership-call.html
- layouts/partials/content/footer/contribute.html
- layouts/partials/content/footer/donate.html
- layouts/shortcodes/calculators/custom-package.html
- layouts/shortcodes/calculators/reimbursement.html
- layouts/shortcodes/fields/twitter.html
- layouts/shortcodes/fields/volunteer.html
> fix calculator embeds

- content/english/support-us/chapter-director/_index.md
- content/english/support-us/chapter-director/application.md
- alias fix for chapter director page
- update link so it works regardless of what it is changed to
> update chapter director links

- config.toml
- package.json
- aligns content in config.toml
- allows for HTML rendering on pages
- updates hugo bin
> fix html rendering

- content/english/about/no-tech-for-ice.md
> fvntr: edits made to ice stance

- content/english/supporters/mailchimp.md
Updating mailchimp sponsort status
---
> fvntr: updating mailchimp sponsor status

- README.md
- content/english/join/_index.md
See #630 
---
- ✅️ Checked to [see if a similar PR has already been opened](https://github.com/techqueria/website/pulls) 🤔️
- ✅️ Reviewed the [contributing guidelines](https://github.com/techqueria/website/blob/master/.github/CONTRIBUTING.md) 🔍️
- ✅️ Added my name to the bottom of the list under the **Contributors** section in the [README.md](https://github.com/techqueria/website/blob/master/README.md) with a link to my personal website or GitHub profile 👥️ (Optional)
> Remove slofile from join page

- README.md
- content/espanol/communities/slack.md
I added some Spanish translation to /slack page and changed a word to make the question read easier. 
---
- [x ] Checked to [see if a similar PR has already been opened](https://github.com/techqueria/website/pulls) 🤔️
- [ x] Reviewed the [contributing guidelines](https://github.com/techqueria/website/blob/master/.github/CONTRIBUTING.md) 🔍️
- [x ] Added my name to the bottom of the list under the **Contributors** section in the [README.md](https://github.com/techqueria/website/blob/master/README.md) with a link to my personal website or GitHub profile 👥️ (Optional)
> Espanol slack update

- content/english/news/2019-03-22-sentry-open-source.md
- content/english/news/2019-04-09-latinx-online-communities.md
- content/english/news/2019-07-18-el-tecolote.md
Fixing typos on website: As a native English speaker, I’m aiming to make the news stories more readable by fixing typos such as misspellings and grammar errors. But I am also trying to be culturally conscious to the fact that people may write/speak in a certain way and that is their style, their flavor. Perhaps something that sounds like awkward wording to me is actually that person’s unique way of expressing themselves. So I’m trying to strike that balance in my edits and not go overboard in over-editing. Please feel free to revise (or reject) my edits according to your judgment.
Articles I edited:
2019-07-18-el-tecolote.md
2019-04-19-latinx-online-communities.md: Fixed some typos but Travel Latina has a typo that I don’t know how to fix, under Why It Started – “I received immediate …
> fixing typos in news articles

- assets/js/components/externalLinks.js
- assets/js/components/twemoji.js
- assets/js/join.js
- content/english/support-us/_index.md
- content/english/support-us/custom-partnerships.md
- layouts/_default/custom/page-support-us.html
- layouts/partials/base/scripts.html
- layouts/partials/base/scripts/twemoji.html
- layouts/partials/content/custom/partnership-call.html
- layouts/partials/content/custom/partnerships-deck.html
- layouts/shortcodes/core-sponsorship-packages.html
- layouts/shortcodes/deck.html
- package.json
- webpack.dev.js
- webpack.prod.js
- fix twemoji
- add partnerships deck
- fix redirect
> fix twemoji

- config.toml
- content/english/donate/match-your-gift/_index.md
- i18n/en.toml
- i18n/es.toml
- layouts/partials/content/footer/donate.html
Required to add career center link to comply with Community Brands agreement
> Donate Updates + Career Center Link

- content/english/news/2020-05-29-solidarity-for-the-black-community.md
signatures for solidarity statement + minor grammar edits
> Add signatueres

- README.md
Previous link 404s
---
- ✅️  Checked to [see if a similar PR has already been opened](https://github.com/techqueria/website/pulls) 🤔️
- ✅️  Reviewed the [contributing guidelines](https://github.com/techqueria/website/blob/master/.github/CONTRIBUTING.md) 🔍️
> Fix link for Spanish readme

- content/english/about/code-of-conduct.md
Minor clarification to CoC
---
> CoC changes

- README.md
> fvntr: changing my name

- content/english/supporters/triplebyte.md
Updating to most recent affiliate link
---
> fvntr: updating triplebyte link

- package.json
Reverts techqueria/website#671
> Revert "Update dependency bulma to ^0.9.0"

- config.toml
- content/support-us/job-postings.md
- content/support-us/marketing-packages.md
> update job postings page

- content/partner.md
- layouts/partials/summit/sponsor-benefits.html
Remove Notion link + update Slack verbiage
> Frances fixes

- content/team/jennifer-konikowski.md
- content/team/kristal-garcia.md
- layouts/_default/custom/page-team.html
- static/_redirects
- create redirect for old podcast site
- update team page
> podcast redirect + team updates

- data/speakers.json
> fvntr: fixing jose's last name

- data/speakers.json
- layouts/partials/summit/raffle-prizes.html
- layouts/partials/summit/schedule/day-3.html
> Minor updates for summit

- content/supporters/northeastern.md
- layouts/partials/content/footer/_index.html
- layouts/partials/content/footer/triplebyte.html
Added description paragraph to silver-sponsor Northeastern University and add Triplebyte to footer.
Resolves #743 and #710 
---
> feat: Add description paragraph to new silver-sponsor and add Triplebyte footer

- content/about/code-of-conduct/_index.md
- content/about/code-of-conduct/report-violation.md
- content/about/contact.md
- content/communities/slack/community-guidelines.md
- remove Slack workflow in guidelines
- add alias to solve #807
> Remove Slack Workflow option in guidelines

- content/supporters/home-depot.md
- layouts/shortcodes/allies.html
Moved home depot to past partner and removed <code>#meta</code> from the join section for allies
resolves https://github.com/techqueria/website/issues/847
resolves https://github.com/techqueria/website/issues/848
Deploy preview: https://deploy-preview-850--techqueria.netlify.app/
---
> Moved partner to past partner, removed #meta from the join page

- config.toml
- content/about/finance.md
Addressing https://github.com/techqueria/website/issues/844 
---
> fvntr: adding 2019 990-N

- content/about/finance.md
Adding link to 2019 debits/credits by category
---
> adding 2019 debits/credits by category

- assets/js/components/lozad.js
This pull request applies style fixes from code review by [CodeFactor](https://www.codefactor.io).
---
For more information, click [here](https://www.codefactor.io/repository/github/techqueria/website).
> Apply fixes from CodeFactor
